apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: urlshortener
spec:
  type: ClusterIP
  selector:
    app: python-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
