sonar.projectKey=urlshortner-microservices
sonar.projectName=URL Shortener Microservices
sonar.projectVersion=1.0

sonar.sources=go-service,python-service,node-service
sonar.exclusions=**/node_modules/**,**/go.sum,**/*.db,**/__pycache__/**,monitoring/**,k8s/**,load-test/**
sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
sonar.coverage.exclusions=**/*
