apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: urlshortener
spec:
  type: ClusterIP
  selector:
    app: go-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
