apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: urlshortener
data:
  GO_SERVICE_URL: "http://go-service:8000"
  NODE_SERVICE_URL: "http://node-service:3000"
  REDIS_HOST: "redis"
