apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  namespace: urlshortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node-service
          image: foysolcse/node-service:v1
          ports:
            - containerPort: 3000
